Add spell
JaanJah/lua-game pull request #8
Opened 2019-08-30 17:38 UTC by hindrekhan

This PR will add spell that can be cast using left mouse button. Currently there is one test spell called fireball. As of now there is no collision detection with spells.

2019-08-30 17:45 UTC, jaanjah requested changes
What is the purpose of this file `spells/.fireBall.lua.swp`?

2019-08-30 17:45 UTC, JaanJah commented on spells/fireBall.lua
> +	extern number time;
Perhaps put shaders in a new file and directory, maybe something like `shaders/fireball`

2019-08-30 17:48 UTC, JaanJah commented
Add more info to PR body, something like `Add spell` can be a bit confusing, perhaps `Add spell feature`.
Also it's worth mentioning what spells this PR will add, is it just fireball or will there be more?

2019-08-30 17:50 UTC, JaanJah commented on sceneManager.lua
> +require "spells/fireBall"
You can just use `fireball`, it's 1 word. Make sure you also rename the files from `fireBall` to `fireball`

2019-09-06 18:03 UTC, JaanJah commented on spells/fireball.lua
> +		self.shader = love.graphics.newShader(shaderCode)
Use spaces here since you are using spaces for the rest of the code

2019-09-06 18:06 UTC, jaanjah approved these changes
Looks good! Some indentation problems, but that is a separate PR topic.

2019-09-06 18:11 UTC, merged